### PR TITLE
#168 State Machine Cleanup

### LINKED ISSUE #168: [RTOS] - State Machine Cleanup
### Description

Currently we have two different implementations of the state machine transition, one in a task and one in a function. I think that either approach would work but we just need to choose and formalize it.

### Acceptance Criteria

Functionally equivalent code that transitions states as before.

### Proposed Solution

This can go two ways:
1. Keep the state machine task and use the function of `queue_state_transition` to actually queue something. Remove the extra stuff in that function too and let the stateMachineDirector handle it
2. Keep everything in that function and remove the stateMachineDirector task. We would still need a way of getting the PDU struct into the file somehow, so we'd either need a new `initStateMachine` function or some extern magic in this case

I think both should work

### PR DESCRIPTION
**Pull request by Peyton-McKee**
## Changes

Moved NERO Statemachine logic to statemachine file. Removed logic from the incrment/decrement/select functions and consolidated into the nero transitition function 

Once again using the state machine director to handle state

General Code Cleanliness

Hide statemachine behind actual use cases of the state machine to create an api that focuses on concepts rather than the technical functionality. 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #168  (issue #)

### CODE REVIEW

**Comment by dyldonahue** [comment]
Just as a note (and i haven't actually reviewed yet) while this is fine, general MPU rearchitecture hasn't begun yet so this will probably have to be further edited in the future to align with the larger changes made

**Comment by Sabramz** [comment]
I just created a develop branch. Can you change this PR to merge into develop?

**Review by jr1221 — APPROVED** [review]
i like this.  the use of the thread vStateMachineDirector should improve performance and **reliability** as no longer are those calling increment, decrement, fault etc. being blocked by the IO required to shut down the car.

Edit: lmk if u have trouble with formatter ur like the 2nd person to use it lol.

**Comment by Sabramz** [comment]
I like it. The send status message in Nero.c will eventually be put in a task to send MPU status over CAN.

**Review by Sabramz — APPROVED** [review]

**Pull request merged**
