### PR TITLE
#203 can button io

### LINKED ISSUE #203: [IO] - Implement CAN based button IO
### Description

Wheel 24A is going to make a return.  

### Acceptance Criteria

- 24A CAN messages from wheel turn into menu state changes 
- Low latency is crucial, but can be improved upon in future PR

### Proposed Solution

See can message specification for wheel. Switch to monitoring incoming CAN messages, and change button state on reception of the message and if that message differs from previous state (keep a cache).

### PR DESCRIPTION
**Pull request by tszwinglitw**
## Changes

- removed old steering io logic and struct
- added handler for steering io can messages

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No merge conflicts
- [x] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #203

### CODE REVIEW

**Review by jr1221 — APPROVED** [review]
Looks good to me.  Did you test it yet?  If not no biggie we can send some fake messages and see what state changes occur.

**Comment by tszwinglitw** [comment]
> Looks good to me. Did you test it yet? If not no biggie we can send some fake messages and see what state changes occur.

- just to confirm: should the uint8 be interpreted bitwise? since the current implementation is actually utilizing the full 0-255 range to indicate a single button_id
- i tested this on the bench with something like `cansend can0 680#0100000000000000` and the switch case print statements are showing as expected

**Comment by jr1221** [comment]
Nah basically since it's event based only one button is signaled at each time.  They are mutually exclusive button presses.

**Comment by tszwinglitw** [comment]
gotcha, should be good to merge if that's the case

**Pull request merged**
